Fix some imprecision in the description of some Updates
danog/MadelineProtoDocs pull request #23
Opened 2020-08-19 22:22 UTC by giulioc008

2020-09-20 14:05 UTC, giulioc008 commented
@danog Can you merge the request ?

2020-09-21 21:57 UTC, danog requested changes

2020-09-21 21:57 UTC, danog commented on docs/API_docs/constructors/updateChannelPinnedMessage.md
This is the exact opposite

2020-09-21 21:57 UTC, danog commented on docs/API_docs/constructors/updateChatParticipantDelete.md
> +**N.B.**: This Update isn't relative to the service message generated by the left event.
What do you mean by this?

2020-09-21 21:57 UTC, danog commented on docs/API_docs/constructors/updateChatParticipantAdd.md
> +**N.B.**: This Update isn't relative to the service message generated by the join event.
What do you mean by this?

2020-09-21 21:57 UTC, danog commented on docs/API_docs/constructors/updateChatPinnedMessage.md
> +**N.B.**: This Update isn't relative to the service message generated by the pin event.
This is the exact opposite

2020-09-22 13:31 UTC, giulioc008 commented on docs/API_docs/constructors/updateChannelPinnedMessage.md
The service message trigger an updateNewMessage, not this update

2020-09-22 13:45 UTC, danog commented on docs/API_docs/constructors/updateChannelPinnedMessage.md
This constructor is still present in the schema, thus it can be triggered in certain conditions.

2020-09-22 21:08 UTC, giulioc008 commented on docs/API_docs/constructors/updateChannelPinnedMessage.md
What conditions ?

2020-09-26 17:46 UTC, giulioc008 commented on docs/API_docs/constructors/updateChatParticipantDelete.md
> +**N.B.**: This Update isn't relative to the service message generated by the left event.
The service message trigger an updateNewMessage, not this update

2020-09-26 17:46 UTC, giulioc008 commented on docs/API_docs/constructors/updateChatParticipantAdd.md
> +**N.B.**: This Update isn't relative to the service message generated by the join event.
The service message trigger an updateNewMessage, not this update

2020-09-26 17:47 UTC, giulioc008 commented on docs/API_docs/constructors/updateChatPinnedMessage.md
> +**N.B.**: This Update isn't relative to the service message generated by the pin event.
The service message trigger an updateNewMessage, not this update

2020-09-27 10:27 UTC, danog commented on docs/API_docs/constructors/updateChatPinnedMessage.md
> +**N.B.**: This Update isn't relative to the service message generated by the pin event.
Then you should write this, instead, linking to the updateNewMessage+messageService page

2020-09-27 10:42 UTC, giulioc008 reviewed
Done

2020-09-27 10:43 UTC, giulioc008 commented
@danog I've done the changes

2020-09-30 21:03 UTC, giulioc008 reviewed
@danog I have done the changes

2020-10-01 08:21 UTC, merged

2020-10-01 11:24 UTC, giulioc008 reviewed
@danog  In what case this updates are relative to the service message ?

2020-10-01 19:57 UTC, danog commented
Well, it depends, but I think it mostly has to do with push notifications or something like that

2020-10-02 05:57 UTC, giulioc008 commented
> Well, it depends, but I think it mostly has to do with push notifications or something like that

Oook